server:
  port: 10010

swagger:
  base-package: com.swagger.demo.controller

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: rebecca-swagger-b